version: '3.8'

services:
  web:
    build:
      context: .  # Path on the host where Dockerfile is located
      dockerfile: Dockerfile
    image: amos-data-portal:latest
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=development
      - DB_HOST=192.168.0.11
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=PgresPW#amotIQ
      - DB_NAME=planungstool
      - DB_NAME1=gemeinsam
